// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfe4Npq7Wyp1v8WXrzCtzGDI69W5wwops',
    appId: '1:749801842827:web:09a305f4e1685a8db24c8e',
    messagingSenderId: '749801842827',
    projectId: 'practice-87591',
    authDomain: 'practice-87591.firebaseapp.com',
    storageBucket: 'practice-87591.firebasestorage.app',
    measurementId: 'G-8R0WJSEY9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vHVbQjaCZYJxpjMv0w2iQwB0xx2Yk8k',
    appId: '1:749801842827:android:a30542140c57db4ab24c8e',
    messagingSenderId: '749801842827',
    projectId: 'practice-87591',
    storageBucket: 'practice-87591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxLjqpySfsrBTNhQHjZek1oDE6YJH8UM',
    appId: '1:749801842827:ios:c5f8a94cefe7c695b24c8e',
    messagingSenderId: '749801842827',
    projectId: 'practice-87591',
    storageBucket: 'practice-87591.firebasestorage.app',
    iosBundleId: 'com.example.undergradApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxLjqpySfsrBTNhQHjZek1oDE6YJH8UM',
    appId: '1:749801842827:ios:c5f8a94cefe7c695b24c8e',
    messagingSenderId: '749801842827',
    projectId: 'practice-87591',
    storageBucket: 'practice-87591.firebasestorage.app',
    iosBundleId: 'com.example.undergradApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfe4Npq7Wyp1v8WXrzCtzGDI69W5wwops',
    appId: '1:749801842827:web:48264c856ca6f0bab24c8e',
    messagingSenderId: '749801842827',
    projectId: 'practice-87591',
    authDomain: 'practice-87591.firebaseapp.com',
    storageBucket: 'practice-87591.firebasestorage.app',
    measurementId: 'G-KNQ11KNZW7',
  );
}
